DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
  r_id int NOT NULL AUTO_INCREMENT,
  r_name varchar(50) NOT NULL,
  PRIMARY KEY (r_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

