
server:
  port: 8555
  servlet:
    context-path: /shop

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop-db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      indent_output: true
  web:
    resources:
      add-mappings: true


logging:
  level:
    org:
      springframework:
        web: ERROR
        security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file.name: /Users/serge/eshop.log